# Generated by Django 5.1.5 on 2025-02-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0002_rename_posted_on_room_posted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='room',
            name='posted_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Landlord.room')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomPhoto',
        ),
    ]
