# Generated by Django 5.1.5 on 2025-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0003_remove_room_image_remove_room_landlord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Flat', 'Flat')], max_length=10, null=True),
        ),
    ]
