# Generated by Django 5.1.5 on 2025-02-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0007_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ManyToManyField(related_name='rooms', to='Landlord.roomimage'),
        ),
    ]
