# Generated by Django 5.1.5 on 2025-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0008_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Flat', 'Flat')], default='Single', max_length=10, null=True),
        ),
    ]
