# Generated by Django 5.1.5 on 2025-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0009_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='is_landlord',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
