# Generated by Django 5.1.5 on 2025-03-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_booked_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
