# Generated by Django 5.1.5 on 2025-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0002_alter_renter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in_date',
            new_name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
