# Generated by Django 5.1.5 on 2025-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0012_rename_created_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rental_duration',
            field=models.CharField(help_text='Duration in months', max_length=40),
        ),
    ]
