# Generated by Django 5.1.5 on 2025-02-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0013_alter_booking_rental_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='is_renter',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
