# Generated by Django 5.1.5 on 2025-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0014_renter_is_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
