# Generated by Django 5.1.5 on 2025-02-21 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landlord', '0011_alter_landlord_user'),
        ('Renter', '0015_remove_review_rating_remove_review_renter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Renter.renter'),
        ),
        migrations.AddField(
            model_name='review',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Landlord.room'),
        ),
    ]
