# Generated by Django 5.1.5 on 2025-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Renter', '0018_alter_review_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True),
        ),
    ]
